apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-ebs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-ebs-sc
  resources:
    requests:
      storage: 10Gi
