apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-metrics-app
  labels:
    app: demo-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-metrics-app
  template:
    metadata:
      labels:
        app: demo-metrics-app
        environment: production
        team: platform
        project: data-collection
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: demo-app
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: metrics
        args:
        - --web.listen-address=:8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-metrics-service
spec:
  selector:
    app: demo-metrics-app
  ports:
  - port: 8080
    targetPort: 8080
