version: "2"
log-pipeline:
  source:
    http:
      path: "/log/ingest"
  processor:
    - add_entries:
        entries:
          - key: "service_name"
            value_expression: '/kubernetes/labels/app'
          - key: "pod_name"
            value_expression: '/kubernetes/pod_name'
          - key: "namespace"
            value_expression: '/kubernetes/namespace_name'
          - key: "container_name"
            value_expression: '/kubernetes/container_name'
    - date:
        from_time_received: true
        destination: "@timestamp"
  sink:
    - opensearch:
        hosts: ["${OPENSEARCH_ENDPOINT}"]
        index: "logs-${service_name}-%{yyyy.MM.dd}"
        aws:
          sts_role_arn: "${INGESTION_ROLE_ARN}"
          region: "${AWS_REGION}"
