version: "2"
otel-trace-pipeline:
  source:
    otel_trace_source:
      path: "/v1/traces"
  processor:
    - trace_peer_forwarder:
  sink:
    - pipeline:
        name: "span-pipeline"
    - pipeline:
        name: "service-map-pipeline"
span-pipeline:
  source:
    pipeline:
      name: "otel-trace-pipeline"
  processor:
    - otel_traces:
  sink:
    - opensearch:
        hosts: ["${OPENSEARCH_ENDPOINT}"]
        index_type: trace-analytics-raw
        aws:
          sts_role_arn: "${INGESTION_ROLE_ARN}"
          region: "${AWS_REGION}"
service-map-pipeline:
  source:
    pipeline:
      name: "otel-trace-pipeline"
  processor:
    - service_map:
  sink:
    - opensearch:
        hosts: ["${OPENSEARCH_ENDPOINT}"]
        index_type: trace-analytics-service-map
        aws:
          sts_role_arn: "${INGESTION_ROLE_ARN}"
          region: "${AWS_REGION}"
