server:
  port: 8082

spring:
  application:
    name: traffic-generator

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.example.traffic: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
